### ISSUE TITLE
Unsealing problem with HA vault cluster

### ISSUE THREAD

**Issue by edro** [pyToshka/vault-autounseal#28]
There is a 3 node vault HA cluster and ConfigMap created:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-autounseal
  namespace: vault
  labels:
    app.kubernetes.io/instance: vault-autounseal
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: vault-autounseal
    app.kubernetes.io/version: v1.0.0
    helm.sh/chart: vault-autounseal-0.5.0
  annotations:
    meta.helm.sh/release-name: vault-autounseal
    meta.helm.sh/release-namespace: vault 
data:
  LOGURU_LEVEL: INFO
  NAMESPACE: vault
  VAULT_KEYS_SECRET: vault-keys
  VAULT_ROOT_TOKEN_SECRET: vault-root-token
  VAULT_SCAN_DELAY: '5'
  VAULT_SECRET_SHARES: '5'
  VAULT_SECRET_THRESHOLD: '3'
  VAULT_URL: http://vault.vault:8200
```

But unsealing process is not completed as you can see in the screenshot below.

![image](https://github.com/pyToshka/vault-autounseal/assets/488474/32b43173-b8c5-4ebb-b37f-6f68359e13a5)
